<!-- BEGIN -->
@import gg.jte.Content
@param Content content
@param Content footer
@param Content header

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Hexlet Javalin Example</title>
    </head>
    <body>
        ${header}
        ${content}
        ${footer}
    </body>
</html>
<!-- END -->
